In [1]:
import selenium
import pandas
from selenium import webdriver

# Question no. 1

In [2]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [3]:
driver.get("https://www.naukri.com/data-analyst-jobs-in-bangalore?k=data%20analyst&l=bangalore")

In [4]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [12]:
for i in driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']"):
    job_title.append(i.get_attribute("title"))
    
for j in driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span"):
    job_location.append(j.get_attribute("title"))
    
for k in driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']"):
    company_name.append(k.get_attribute("title"))
    
for l in driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span"):
    experience_required.append(l.get_attribute("title"))

In [15]:
jobs=pandas.DataFrame({})
jobs["Job Title"]=job_title[0:10]
jobs["Job Location"]=job_location[0:10]
jobs["Company Name"]=company_name[0:10]
jobs["Experience Required"]=experience_required[0:10]
jobs

,Job Title,Job Location,Company Name,Experience Required
0,Data Analyst,Bangalore/Bengaluru(Devalapur),Super India Tech Mark,0-2 Yrs
1,Data Analyst,Bangalore/Bengaluru,tech mahindra ltd,4-8 Yrs
2,Data Analyst,Bangalore/Bengaluru,CONDUENT BUSINESS SERVICES INDIA LLP,1-2 Yrs
3,Data Analyst,Bangalore/Bengaluru,GlaxoSmithKline Pharmaceuticals Limited,2-7 Yrs
4,Business Data Analyst - MIS & Reporting,"Mumbai, Bangalore/Bengaluru",INTERTRUST GROUP,3-7 Yrs
5,Data Analyst,Bangalore/Bengaluru,Xiaomi,2-6 Yrs
6,Inviting Business Analyst –Data Science and I...,Bangalore/Bengaluru,GENPACT India Private Limited,0-4 Yrs
7,Hiring For Data Analyst,"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",Concentrix Daksh Services India Private Limited.,2-7 Yrs
8,Senior Data Analyst,Bangalore/Bengaluru,Cerner,3-5 Yrs
9,Senior Data Analyst,Bangalore/Bengaluru,Cerner Corporation,4-9 Yrs

In [17]:
driver.close()

# Question no. 2

In [1]:
import selenium
import pandas as pd
from selenium import webdriver

In [2]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [46]:
job=[]
location=[]
name=[]
desc=[]

In [47]:
driver.get("https://www.naukri.com/job-listings-data-scientist-cronj-it-technologies-private-limited-bangalore-bengaluru-0-to-1-years-310321002339?src=jobsearchDesk&sid=16175530616141879&xp=1&px=1")

In [48]:
title=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title)
loc=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc)
na=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na)

for i in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(i.text.replace('\n',''))

In [49]:
driver.get("https://www.naukri.com/job-listings-opportunity-for-data-scientist-internship-bengaluru-corner-stone-solutions-bangalore-bengaluru-0-to-1-years-240620007489?src=jobsearchDesk&sid=16175530616141879&xp=2&px=1")
title1=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title1)
loc1=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc1)
na1=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na1)

for j in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(j.text.replace('\n',''))

In [50]:
driver.get("https://www.naukri.com/job-listings-data-scientist-analyst-becton-dickinson-india-pvt-ltd-bangalore-bengaluru-5-to-10-years-220321002877?src=jobsearchDesk&sid=16175530616141879&xp=3&px=1")
title2=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title2)
loc2=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc2)
na2=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na2)

for k in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(k.text.replace('\n',''))

In [51]:
driver.get("https://www.naukri.com/job-listings-data-scientist-machine-learning-augmatrixgo-bangalore-bengaluru-2-to-5-years-140121905423?src=jobsearchDesk&sid=16175530616141879&xp=4&px=1")
title3=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title3)
loc3=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc3)
na3=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na3)

for l in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(l.text.replace('\n',''))

In [53]:
driver.get("https://www.naukri.com/job-listings-associate-data-scientist-crm-loyalty-shell-india-markets-private-limited-bangalore-bengaluru-3-to-5-years-010421904445?src=jobsearchDesk&sid=16175530616141879&xp=10&px=1")
title4=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title4)
loc4=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc4)
na4=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na4)

for m in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(m.text.replace('\n',''))

In [55]:
driver.get("https://www.naukri.com/job-listings-data-scientist-dun-bradstreet-information-services-india-private-limited-bangalore-bengaluru-2-to-5-years-010421501056?src=jobsearchDesk&sid=16175530616141879&xp=12&px=1")
title5=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title5)
loc5=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc5)
na5=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na5)

for n in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(n.text.replace('\n',''))

In [57]:
driver.get("https://www.naukri.com/job-listings-data-scientist-redcan-it-services-llp-bangalore-bengaluru-0-to-0-years-010421004572?src=jobsearchDesk&sid=16175530616141879&xp=13&px=1")
title6=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title6)
loc6=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc6)
na6=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na6)

for o in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(o.text.replace('\n',''))

In [58]:
driver.get("https://www.naukri.com/job-listings-jr-data-scientist-multi-recruit-bangalore-bengaluru-1-to-6-years-310321500466?src=jobsearchDesk&sid=16175530616141879&xp=14&px=1")
title7=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title7)
loc7=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc7)
na7=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na7)

for p in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(p.text.replace('\n',''))

In [60]:
driver.get("https://www.naukri.com/job-listings-senior-data-scientist-machine-vision-solutions-onx-software-systems-pvt-ltd-bangalore-bengaluru-5-to-9-years-230321001143?src=jobsearchDesk&sid=16175530616141879&xp=15&px=1")
title8=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title8)
loc8=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc8)
na8=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na8)

for q in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(q.text.replace('\n',''))

In [61]:
driver.get("https://www.naukri.com/job-listings-opening-for-the-position-data-scientist-pluto-seven-business-solutions-p-limited-bangalore-bengaluru-2-to-6-years-010421002118?src=jobsearchDesk&sid=16175530616141879&xp=19&px=1")
title9=driver.find_element_by_xpath("//h1[@class='jd-header-title']").get_attribute("title")
job.append(title9)
loc9=driver.find_element_by_xpath("//span[@class='location ']/a").get_attribute("title")
location.append(loc9)
na9=driver.find_element_by_xpath("//div[@class='jd-header-comp-name']/a").get_attribute("title")
name.append(na9)

for r in driver.find_elements_by_xpath("//div[@class='dang-inner-html']"):
    desc.append(r.text.replace('\n',''))

In [62]:
data_science=pd.DataFrame({})
data_science["Job Title"]=job
data_science["Location"]=location
data_science["Company Name"]=name
data_science["Job Description"]=desc
data_science

,Job Title,Location,Company Name,Job Description
0,Data Scientist,Jobs in Bangalore/Bengaluru,CronJ IT Technologies Private Limited Careers,Responsibilities and DutiesCreate innovative s...
1,Opportunity For Data Scientist Internship - Be...,Jobs in Bangalore/Bengaluru,Corner Stone Solutions Careers,Location - Bangalore / BengaluruDuration- 6 Mo...
2,Data Scientist/ Analyst,Jobs in Bangalore/Bengaluru,Becton Dickinson India Pvt. Ltd Careers,Roles and Responsibilitiesob Description Summa...
3,Data Scientist - Machine Learning,Jobs in Bangalore/Bengaluru,AugmatrixGo Careers,Roles and Responsibilities- Selecting features...
4,Associate Data Scientist - CRM & Loyalty,Jobs in Bangalore/Bengaluru,Shell India Markets Private Limited Careers,The RoleGeneral Position DefinitionThis role w...
5,Data Scientist,Jobs in Bangalore/Bengaluru,DUN & BRADSTREET INFORMATION SERVICES INDIA PR...,"Key Skills: Machine Learning, Data Engineeri..."
6,Data Scientist,Jobs in Bangalore/Bengaluru,Redcan IT Services LLP Careers,Free Training program for Data science and Mac...
7,Jr. Data Scientist,Jobs in Bangalore/Bengaluru,Multi Recruit Careers,Qualification B.Tech/B.E. (Computers) Roles a...
8,Senior Data Scientist (Machine Vision solutions),Jobs in Bangalore/Bengaluru,ONX Software Systems Pvt Ltd Careers,Senior Data Scientist (Machine Vision solution...
9,Job Opening For the Position Data Scientist,Jobs in Bangalore/Bengaluru,Pluto seven business solutions (p) limited Car...,Company Background:Pluto7 is a Google Premier ...

# Question no.3

In [1]:
import selenium 
import pandas as pd
from selenium import webdriver

In [2]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [3]:
driver.get("https://www.naukri.com/data-scientist-jobs?k=data%20scientist&cityTypeGid=9508&ctcFilter=3to6")

In [16]:
job_title=[]
location=[]
name=[]
experience=[]

In [17]:
for i in driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']"):
    job_title.append(i.get_attribute("title"))
    
for j in driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span"):
    location.append(j.get_attribute("title"))
    
for k in driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']"):
    name.append(k.get_attribute("title"))
    
for l in driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span"):
    experience.append(l.get_attribute("title"))

In [19]:
jobs=pd.DataFrame({})
jobs["Job Title"]=job_title[0:10]
jobs["Location"]=location[0:10]
jobs["Company Name"]=name[0:10]
jobs["Experience Required"]=experience[0:10]
jobs

,Job Title,Location,Company Name,Experience Required
0,Developer - Data Science,Delhi / NCR,ICL Systems India Private Limited,3-5 Yrs
1,Data Scientist - IBM Garage,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",IBM India Pvt. Limited,5-8 Yrs
2,Data Scientist/Data Analyst - Python/Machine L...,"Mumbai, Ghaziabad",Change leaders,5-10 Yrs
3,Females Required- Data Scientist- Noida,"Noida, Gurgaon/Gurugram, Delhi / NCR",Randstad,3-7 Yrs
4,Data Scientist,"Ghaziabad, Faridabad, Delhi / NCR",Amity University,6-8 Yrs
5,Data Scientist - Python & Machine Learning,"Hyderabad/Secunderabad, Pune, Bangalore/Bengal...",FUTURES AND CAREERS,2-7 Yrs
6,Data Scientist - Python & Machine Learning,"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",FUTURES AND CAREERS,2-7 Yrs
7,Data Scientist - Python / Machine Learning / T...,"Mumbai, Hyderabad/Secunderabad, Bangalore/Beng...",FUTURES AND CAREERS,3-8 Yrs
8,Data Scientist - Python & Machine Learning,"Hyderabad/Secunderabad, Bangalore/Bengaluru, D...",FUTURES AND CAREERS,2-7 Yrs
9,Required- Data Scientist (NLP)-Axis Bank - 6 m...,"Kolkata, New Delhi, Hyderabad/Secunderabad, Pu...",Axis Bank Limited,4-9 Yrs

# Question no.4

In [20]:
driver.get("https://www.glassdoor.co.in/Job/noida-data-scientist-jobs-SRCH_IL.0,5_IC4477468_KO6,20.htm")

In [21]:
company=[]
post=[]
rating=[]

In [33]:
for b in driver.find_elements_by_xpath("//span[@class='css-19pjha7 e1cjmv6j1']"):
    post.append(b.text)
for c in driver.find_elements_by_xpath("//div[@class='d-flex align-items-end pl-std css-mi55ob']"):
    rating.append(c.text)

In [37]:
for a in driver.find_elements_by_xpath("//div[@class='d-flex justify-content-between align-items-start']"):
    company.append(a.text)

In [39]:
job=pd.DataFrame({})
job["Company Name"]=company[0:10]
job["Job posted ago"]=rating[0:10]
job["Rating"]=post[0:10]
job

                   Company Name Job posted ago Rating
0                Biz2Credit Inc           30d+    3.8
1                      Techlive           30d+    5.0
2                         Adobe             9d    4.4
3  Salasar New Age Technologies           30d+    4.4
4  Salasar New Age Technologies           30d+    3.8
5                     Microsoft           30d+    4.0
6                       Genpact             4d    4.2
7                           JLL            24h    5.0
8                    MasterCard             1d    3.6
9                       Asquero            10d    5.0

# Question no.5

In [1]:
import selenium
import pandas as pd
from selenium import webdriver

In [2]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [3]:
driver.get("https://www.glassdoor.co.in/Salaries/new-delhi-data-scientist-salary-SRCH_IL.0,9_IM1083_KO10,24.htm?clickSource=searchBtn")

In [42]:
company_name=[]
min_salary=[]
max_salary=[]
average_salary=[]

In [43]:
for d in driver.find_elements_by_xpath("//p[@class='m-0 ']"):
    company_name.append(d.text)

In [63]:
for e in driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__values d-flex justify-content-between ']"):
    min_salary.append(e.text.split("\n")[0])
    max_salary.append(e.text.split("\n")[1])

In [65]:
for f in driver.find_elements_by_xpath("//div[@class='col-2 d-none d-md-flex flex-row justify-content-end']/strong"):
    average_salary.append(f.text)

In [67]:
number=[]
for g in driver.find_elements_by_xpath("//p[@class='css-1uyte9r css-1kuy7z7 m-0 ']"):
    number.append(g.text)

In [70]:
jobs=pd.DataFrame({})
jobs["Company Name"]=company_name[0:10]
jobs["Minimum Salary"]=min_salary[0:10]
jobs["Maximum Salary"]=max_salary[0:10]
jobs["Average Salary"]=average_salary[0:10]
jobs["Number of Salaries"]=number[0:10]
jobs

,Company Name,Minimum Salary,Maximum Salary,Average Salary,Number of Salaries
0,Tata Consultancy Services,₹336K,"₹1,080K","₹ 6,01,000",14 salaries
1,Accenture,"₹1,080K","₹2,222K","₹ 11,51,207",14 salaries
2,Delhivery,₹336K,"₹11,669K","₹ 12,34,207",14 salaries
3,IBM,₹579K,"₹2,741K","₹ 7,63,825",13 salaries
4,Ericsson-Worldwide,₹452K,"₹1,619K","₹ 7,32,209",12 salaries
5,UnitedHealth Group,₹589K,"₹1,500K","₹ 13,88,910",10 salaries
6,Valiance Solutions,₹350K,"₹1,471K","₹ 8,18,515",9 salaries
7,Innovaccer,"₹1,050K","₹1,702K","₹ 12,01,403",8 salaries
8,ZS Associates,₹504K,"₹1,817K","₹ 10,00,000",7 salaries
9,EXL Service,₹623K,"₹1,500K","₹ 11,90,000",7 salaries

# Question no.6

In [71]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [72]:
driver.get("https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off&page=1")

In [93]:
brand=[] 
desc=[]
price=[]
discount=[]

In [94]:
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"):
        brand.append(j.text)
    for k in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        price.append(k.text)
    for l in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span"):
        discount.append(l.text)
    for m in driver.find_elements_by_xpath("//a[@class='IRpwTa']"):
        desc.append(m.get_attribute("title"))

In [96]:
Sunglasses=pd.DataFrame({})
Sunglasses["Brand Name"]=brand[0:100]
Sunglasses["Price"]=price[0:100]
Sunglasses["Discount"]=discount[0:100]
Sunglasses["Description"]=desc[0:100]
Sunglasses

,Brand Name,Price,Discount,Description
0,ROYAL SON,₹399,73% off,Mirrored Aviator Sunglasses (58)
1,ROYAL SON,₹664,66% off,"Polarized, UV Protection Round Sunglasses (49)"
2,Fastrack,₹758,15% off,UV Protection Wayfarer Sunglasses (Free Size)
3,PIRASO,₹250,84% off,UV Protection Aviator Sunglasses (54)
4,Fastrack,₹666,16% off,UV Protection Rectangular Sunglasses (Free Size)
...,...,...,...,...
95,ROZZETTA CRAFT,₹404,79% off,UV Protection Retro Square Sunglasses (88)
96,Singco India,₹195,80% off,UV Protection Wayfarer Sunglasses (32)
97,Fastrack,₹674,15% off,UV Protection Wayfarer Sunglasses (Free Size)
98,Singco India,₹329,72% off,UV Protection Wayfarer Sunglasses (56)
99,ROYAL SON,₹599,70% off,UV Protection Aviator Sunglasses (58)

# Question no.7

In [1]:
import selenium
import pandas
from selenium import webdriver

In [2]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [4]:
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZE3ENS&marketplace=FLIPKART")

In [20]:
rating=[]
review=[]
full_review=[]

In [21]:
for a in range(0,10):
    for b in driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']"):
        rating.append(b.text)
    for c in driver.find_elements_by_xpath("//p[@class='_2-N8zT']"):
        review.append(c.text)
    for d in driver.find_elements_by_xpath("//div[@class='t-ZTKy']"):
        full_review.append(d.text.replace('\n\n','').replace('\n',' and '))

['The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide camera and New Night mode is excellent and Long battery life',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'Previously I was using one plus 3t it was a great phone and And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 and I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display and But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red and My experience after using 3 weeks and 1. The delivery ... and READ MORE',
 'Amazing Powerful and Durable Gadget.I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.I’ve attached my puppy pics and no fi... and READ MORE',
 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment. and If you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you. and Cameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !',
 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with... and READ MORE',
 'Value for money❤️❤️ and Its awesome mobile phone in the world ... and Display was very good and bright .. and Trust me freinds you r never regret after Buying.. and Just go for it.... and I love this phone and i switch to iphone x to 11',
 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.',
 '*Review after 10 months of usage* and Doesn\'t seem bulky with decent touch and camera. The "standard maintained" quality of IPhone. Go for it, if your budget is not more enough for pro models. It\'s a value for money among the 11 series Stereo speakers are so good, you will love the stereo sound. Battery backup is not decent but still better than Iphone 7 and 8.Processor is fast, the phone doesn\'t lag at all even with heavy games, waterproof, faster face id and with no fingerprint scanners. The ca... and READ MORE',
 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.Camera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃Battery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba... and READ MORE',
 'The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide camera and New Night mode is excellent and Long battery life',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'Previously I was using one plus 3t it was a great phone and And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 and I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display and But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red and My experience after using 3 weeks and 1. The delivery ... and READ MORE',
 'Amazing Powerful and Durable Gadget.I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.I’ve attached my puppy pics and no fi... and READ MORE',
 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment. and If you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you. and Cameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !',
 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with... and READ MORE',
 'Value for money❤️❤️ and Its awesome mobile phone in the world ... and Display was very good and bright .. and Trust me freinds you r never regret after Buying.. and Just go for it.... and I love this phone and i switch to iphone x to 11',
 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.',
 '*Review after 10 months of usage* and Doesn\'t seem bulky with decent touch and camera. The "standard maintained" quality of IPhone. Go for it, if your budget is not more enough for pro models. It\'s a value for money among the 11 series Stereo speakers are so good, you will love the stereo sound. Battery backup is not decent but still better than Iphone 7 and 8.Processor is fast, the phone doesn\'t lag at all even with heavy games, waterproof, faster face id and with no fingerprint scanners. The ca... and READ MORE',
 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.Camera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃Battery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba... and READ MORE',
 'The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide camera and New Night mode is excellent and Long battery life',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'Previously I was using one plus 3t it was a great phone and And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 and I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display and But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red and My experience after using 3 weeks and 1. The delivery ... and READ MORE',
 'Amazing Powerful and Durable Gadget.I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.I’ve attached my puppy pics and no fi... and READ MORE',
 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment. and If you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you. and Cameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !',
 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with... and READ MORE',
 'Value for money❤️❤️ and Its awesome mobile phone in the world ... and Display was very good and bright .. and Trust me freinds you r never regret after Buying.. and Just go for it.... and I love this phone and i switch to iphone x to 11',
 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.',
 '*Review after 10 months of usage* and Doesn\'t seem bulky with decent touch and camera. The "standard maintained" quality of IPhone. Go for it, if your budget is not more enough for pro models. It\'s a value for money among the 11 series Stereo speakers are so good, you will love the stereo sound. Battery backup is not decent but still better than Iphone 7 and 8.Processor is fast, the phone doesn\'t lag at all even with heavy games, waterproof, faster face id and with no fingerprint scanners. The ca... and READ MORE',
 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.Camera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃Battery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba... and READ MORE',
 'The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide camera and New Night mode is excellent and Long battery life',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'Previously I was using one plus 3t it was a great phone and And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 and I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display and But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red and My experience after using 3 weeks and 1. The delivery ... and READ MORE',
 'Amazing Powerful and Durable Gadget.I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.I’ve attached my puppy pics and no fi... and READ MORE',
 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment. and If you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you. and Cameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !',
 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with... and READ MORE',
 'Value for money❤️❤️ and Its awesome mobile phone in the world ... and Display was very good and bright .. and Trust me freinds you r never regret after Buying.. and Just go for it.... and I love this phone and i switch to iphone x to 11',
 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.',
 '*Review after 10 months of usage* and Doesn\'t seem bulky with decent touch and camera. The "standard maintained" quality of IPhone. Go for it, if your budget is not more enough for pro models. It\'s a value for money among the 11 series Stereo speakers are so good, you will love the stereo sound. Battery backup is not decent but still better than Iphone 7 and 8.Processor is fast, the phone doesn\'t lag at all even with heavy games, waterproof, faster face id and with no fingerprint scanners. The ca... and READ MORE',
 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.Camera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃Battery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba... and READ MORE',
 'The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide camera and New Night mode is excellent and Long battery life',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'Previously I was using one plus 3t it was a great phone and And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 and I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display and But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red and My experience after using 3 weeks and 1. The delivery ... and READ MORE',
 'Amazing Powerful and Durable Gadget.I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.I’ve attached my puppy pics and no fi... and READ MORE',
 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment. and If you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you. and Cameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !',
 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with... and READ MORE',
 'Value for money❤️❤️ and Its awesome mobile phone in the world ... and Display was very good and bright .. and Trust me freinds you r never regret after Buying.. and Just go for it.... and I love this phone and i switch to iphone x to 11',
 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.',
 '*Review after 10 months of usage* and Doesn\'t seem bulky with decent touch and camera. The "standard maintained" quality of IPhone. Go for it, if your budget is not more enough for pro models. It\'s a value for money among the 11 series Stereo speakers are so good, you will love the stereo sound. Battery backup is not decent but still better than Iphone 7 and 8.Processor is fast, the phone doesn\'t lag at all even with heavy games, waterproof, faster face id and with no fingerprint scanners. The ca... and READ MORE',
 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.Camera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃Battery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba... and READ MORE',
 'The Best Phone for the MoneyThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.Compelling ultra-wide camera and New Night mode is excellent and Long battery life',
 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .',
 'Previously I was using one plus 3t it was a great phone and And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 and I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display and But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red and My experience after using 3 weeks and 1. The delivery ... and READ MORE',

In [24]:
iphone=pandas.DataFrame({})
iphone["Rating"]=rating
iphone["Review"]=review
iphone["Full Review"]=full_review
iphone

,Rating,Review,Full Review
0,5,Brilliant,The Best Phone for the MoneyThe iPhone 11 offe...
1,5,Perfect product!,Amazing phone with great cameras and better ba...
2,5,Worth every penny,Previously I was using one plus 3t it was a gr...
3,5,Great product,Amazing Powerful and Durable Gadget.I’m am ver...
4,5,Highly recommended,iphone 11 is a very good phone to buy only if ...
...,...,...,...
95,5,Perfect product!,It’s a must buy who is looking for an upgrade ...
96,5,Perfect product!,Value for money❤️❤️ and Its awesome mobile pho...
97,5,Fabulous!,This is my first iOS phone. I am very happy wi...
98,5,Wonderful,*Review after 10 months of usage* and Doesn't ...
99,5,Worth every penny,Best budget Iphone till date ❤️ go for it guys...

# Question no.8

In [25]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [26]:
driver.get("https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off")

In [27]:
brand=[] 
desc=[]
price=[]
discount=[]

In [34]:
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"):
        brand.append(j.text)
    for k in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        price.append(k.text)
    for l in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span"):
        discount.append(l.text)
    for m in driver.find_elements_by_xpath("//a[@class='IRpwTa']"):
        desc.append(m.get_attribute("title"))

In [38]:
shoes=pandas.DataFrame({})
shoes["Brand Name"]=brand[0:100]
shoes["Price"]=price[0:100]
shoes["Discount"]=discount[0:100]
shoes["Description"]=desc[0:100]
shoes

,Brand Name,Price,Discount,Description
0,Extoes,₹629,57% off,Relaxed Attractive Combo pack of 3 Sneakers Fo...
1,well feet,₹399,33% off,sneaker for mens and boys Sneakers For Men
2,Chevit,₹499,72% off,Perfect & Affordable Combo Pack of 02 Pairs Sn...
3,Robbie jones,₹399,60% off,Casual Sneakers Shoes For Men Sneakers For Men
4,Chevit,₹474,76% off,Combo Pack of 4 Casual Sneakers With Sneakers ...
...,...,...,...,...
95,ROCKFIELD,₹396,60% off,Sneakers for men(black_6) Sneakers For Men
96,"""trend""",₹479,88% off,White Sneakers Sneakers For Men
97,Chevit,₹322,67% off,Sneakers Sneakers For Men
98,Echor,₹570,42% off,Sneakers For Men
99,SHOEFLY,₹269,73% off,Sneakers For Men

# Question no.9

In [17]:
import selenium
import pandas as pd
from selenium import webdriver
import time

In [2]:
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [3]:
driver.get("https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0%2C6657.0_13105.0_6657.0%20TO%2013105.0")

In [27]:
brands=[]
desc=[]

In [28]:
for i in range(0,2):
    for j in driver.find_elements_by_xpath("//h3[@class='product-brand']"):
        brands.append(j.text)
    for k in driver.find_elements_by_xpath("//h4[@class='product-product']"):
        desc.append(k.text)
    time.sleep(3)
    url=driver.find_element_by_xpath("//li[@class='pagination-next']/a").get_attribute("href")
    driver.get(url)

In [36]:
prices=[]
for m in range(0,4):
    for l in driver.find_elements_by_xpath("//span[@class='product-discountedPrice']"):
        prices.append(l.text)

In [39]:
shoes=pd.DataFrame({})
shoes["Brand Name"]=brands
shoes["Price"]=prices[0:100]
shoes["Short Description"]=desc
shoes

              Brand Name      Price               Short Description
0                 ADIDAS   Rs. 7497  Men Harden Stepback Basketball
1                 ADIDAS   Rs. 8091     Men Supernova Running Shoes
2       ADIDAS Originals   Rs. 7641      Men Smooth Runner Sneakers
3                 Reebok   Rs. 7413  Unisex Zig Kinetica II Running
4       ADIDAS Originals   Rs. 8049   Men OZWEEGO Big Logo Sneakers
..                   ...        ...                             ...
95                  Puma  Rs. 10399   Men Ignite Sock Plus Sneakers
96  Heel & Buckle London   Rs. 7499      Men Leather Formal Loafers
97             Cole Haan   Rs. 8792                Leather Sneakers
98                  Puma   Rs. 7199                    casual shoes
99           Birkenstock   Rs. 6996  Women Yara Oiled Leather Flats

[100 rows x 3 columns]

# Question no.10

In [2]:
import pandas as pd
import selenium
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
driver=webdriver.Chrome("C:\\Users\\batha\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [20]:
title=[]
rating=[]
price=[]

In [4]:
driver.get("https://www.amazon.in/s?k=laptops&i=computers&rh=n%3A1375424031%2Cp_n_feature_thirteen_browse-bin%3A12598163031%7C16757432031&dc&qid=1617877917&rnid=12598141031&ref=sr_nr_p_n_feature_thirteen_browse-bin_16")

In [21]:
for d in driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']"):
    title.append(d.text)
for e in driver.find_elements_by_xpath("//span[@class='a-price-whole']"):
    price.append(e.text)

In [31]:
#locating rating
urls=driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")
ur=[]
for i in urls[:10]:
    ur.append(i.get_attribute('href'))
for url in ur:
    driver.get(url)
    try:
        rate=driver.find_element_by_xpath("//span[@id='acrCustomerReviewText']")
        rate.click()
        ratings=driver.find_element_by_xpath("//span[@class='a-size-medium a-color-base']")
        rating.append(ratings.text)
        
    except NoSuchElementException  as e:
        rating.append("NO Rating")

In [33]:
laptop=pd.DataFrame({})
laptop["Title"]=title[0:10]
laptop["Price"]=price[0:10]
laptop["Rating"]=rating
laptop

                                               Title     Price        Rating
0  ASUS ROG G703GI-E5148T 17.3-inch FHD 144Hz/3ms...  5,22,077  3.9 out of 5
1  HP Envy 11th Gen Core i7 Processor 13.3-inch F...  1,32,519     NO Rating
2  Lenovo IdeaPad Gaming 3 10th Gen Intel Core i7...    76,990  4.4 out of 5
3  Mi Notebook Horizon Edition 14 Intel Core i7-1...    58,999  4.3 out of 5
4  ASUS VivoBook S S14 Intel Core i7-1165G7 11th ...    77,990  4.3 out of 5
5  (Renewed) Lenovo ThinkPad X1 Carbon Laptop (CO...    55,290     NO Rating
6  (Renewed) Dell Latitude 7389 Laptop (CORE I7 7...    57,990     NO Rating
7  (Renewed) HP Pavilion 15-Cs1002txin 2018 15.6-...    68,490     NO Rating
8  LifeDigital ZED AIR CX7 15.6 IPS FHD Screen Bl...    39,990  3.5 out of 5
9  Alienware Gaming AW17R5-7405SLV-PUS 8th Gen In...  3,32,171  3.8 out of 5